// Actual ACTXPresale.sol ABI — deployed on Base Sepolia
// Contract: 0xA5c93F78ee3eD5395d2fa92e8ce8f856F292fc9e

export const PRESALE_ABI = [
  // === View Functions ===
  'function isQualified(address wallet) view returns (bool)',
  'function getWalletTier(address wallet) view returns (uint8)',
  'function getPurchase(address wallet) view returns (uint256 totalTokens, uint256 totalSpentUsdc, uint256 claimed)',
  'function getClaimable(address wallet) view returns (uint256)',
  'function getLockedBalance(address wallet) view returns (uint256)',
  'function getTierConfig(uint8 tier) view returns (uint256 priceUsdc, uint256 maxSpendUsdc)',
  'function getPresaleStats() view returns (uint256 poolTotal, uint256 poolRemaining, uint256 totalUsdcRaised, uint256 totalParticipants, bool presaleOpen, bool tgeTriggered, uint256 tgeTimestamp, uint256 version)',
  'function poolRemaining() view returns (uint256)',
  'function poolTotal() view returns (uint256)',
  'function totalUsdcRaised() view returns (uint256)',
  'function totalParticipants() view returns (uint256)',
  'function presaleOpen() view returns (bool)',
  'function tgeTriggered() view returns (bool)',
  'function tgeTimestamp() view returns (uint256)',
  'function actxToken() view returns (address)',
  'function usdc() view returns (address)',
  'function usdcRecipient() view returns (address)',
  'function version() view returns (uint256)',
  'function maxParticipants() pure returns (uint256)',
  'function maxTokensPerFounder() pure returns (uint256)',
  'function paused() view returns (bool)',

  // === Write Functions ===
  'function purchase(uint256 usdcAmount) external',
  'function claim() external',
  'function qualifyWallet(address wallet) external',
  'function qualifyWallets(address[] wallets) external',
  'function disqualifyWallet(address wallet) external',
  'function setWalletTier(address wallet, uint8 tier) external',
  'function setWalletTiers(address[] wallets, uint8[] tiers) external',
  'function updateTierConfig(uint8 tier, uint256 priceUsdc, uint256 maxSpendUsdc) external',
  'function fundPool(uint256 amount) external',
  'function openPresale() external',
  'function closePresale() external',
  'function triggerTGE() external',
  'function setUsdcRecipient(address newRecipient) external',
  'function withdrawUnsoldTokens(address to) external',
  'function rescueETH(address to) external',
  'function rescueToken(address token, address to, uint256 amount) external',
  'function pause() external',
  'function unpause() external',

  // === Events ===
  'event WalletQualified(address indexed wallet)',
  'event WalletDisqualified(address indexed wallet)',
  'event WalletTierSet(address indexed wallet, uint8 tier)',
  'event TokensPurchased(address indexed buyer, uint8 tier, uint256 usdcAmount, uint256 tokenAmount, uint256 poolRemaining)',
  'event TGETriggered(uint256 timestamp)',
  'event TokensClaimed(address indexed wallet, uint256 amount, uint256 totalClaimed)',
  'event PresaleOpened(uint256 timestamp)',
  'event PresaleClosed(uint256 timestamp)',
  'event PoolFunded(address indexed funder, uint256 amount, uint256 newPoolTotal)',
  'event TierConfigUpdated(uint8 indexed tier, uint256 priceUsdc, uint256 maxSpendUsdc)',
  'event UsdcRecipientUpdated(address indexed oldRecipient, address indexed newRecipient)',
  'event UnsoldTokensWithdrawn(address indexed to, uint256 amount)',
  'event ContractUpgraded(address indexed newImplementation, uint256 version)',

  // === Errors ===
  'error NotQualified()',
  'error NoTierAssigned()',
  'error PresaleNotOpen()',
  'error PresaleAlreadyOpen()',
  'error PoolExhausted()',
  'error ExceedsMaxSpend(uint256 requested, uint256 remaining)',
  'error ExceedsTokenCap(uint256 requested, uint256 remaining)',
  'error MaxParticipantsReached()',
  'error TGEAlreadyTriggered()',
  'error TGENotTriggered()',
  'error NothingToClaim()',
  'error ZeroAddress()',
  'error ZeroAmount()',
  'error InvalidTier()',
  'error PresaleStillOpen()',
  'error ETHTransferFailed()',
  'error CannotRescueACTX()',
] as const;
